@host = http://127.0.0.1:3005

### /posts ###########################

GET {{host}}/posts

###

GET {{host}}/posts?timeSort=asc

###

GET {{host}}/posts?q=test

###

POST {{host}}/post
Content-Type: application/json

{
    "type": "person",
    "content": "Hello! I'm Zoe."
}

###

DELETE {{host}}/post/664acdd037326c3e11e79124


### delete ALL posts

DELETE {{host}}/posts

###

PATCH {{host}}/post/664acd9d37326c3e11e79120
Content-Type: application/json

{
    "tags": ["學習", " "]
}


### /users ############################

GET {{host}}/users

###

GET {{host}}/users/663adeb90720cbbe100af83e

###

POST {{host}}/users
Content-Type: application/json

{
    "nickname": "Zoe",
    "email": "zoe@example.com",
    "photo": ""
}

###

PATCH {{host}}/users/663adeb90720cbbe100af83e
Content-Type: application/json

{
    "nickname": "Albert"
}
