@host = http://127.0.0.1:3005

###

GET {{host}}/posts

###

POST {{host}}/posts
Content-Type: application/json

{
    "user": "663ae1bad00ea08dc6f1c239",
    "content": "test by Zoe"
}

###

DELETE {{host}}/posts/663adff4b69eb9a42f6e6757




###

GET {{host}}/users

###

POST {{host}}/users
Content-Type: application/json

{
    "nickname": "Zoe",
    "email": "zoe@example.com",
    "photo": ""
}
