@host = http://127.0.0.1:3005

### /posts ###########################

GET {{host}}/posts

###

GET {{host}}/posts?timeSort=asc

###

GET {{host}}/posts?q=test

###

POST {{host}}/post
Content-Type: application/json

{
    "type": "person",
    "content": "   "
}

###

DELETE {{host}}/post/664acdd037326c3e11e79124


### delete ALL posts

DELETE {{host}}/posts

###

PATCH {{host}}/post/664acd9d37326c3e11e79120
Content-Type: application/json

{
    "tags": ["學習", " "]
}


### /users ############################

GET {{host}}/users

###

POST {{host}}/user/sign_up
Content-Type: application/json

{
    "nickname": "Zoe3",
    "email": "zoe3@example.com",
    "password": "this is zoe3",
    "photo": ""
}

###

POST {{host}}/user/sign_in
Content-Type: application/json

{
    "email": "zoe3@example.com",
    "password": "this is zoe3"
}

###

PATCH {{host}}/user/updatePassword
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY2NTgzNTZhM2YzMGU2ZTg1ZDI2NDI4ZCIsImlhdCI6MTcxNzA1Njg4OCwiZXhwIjoxNzE3MzE2MDg4fQ.hF2MgzOyZLZg0Z4pMkOZCK3jzkEwmeE-lI2Wh-3UUXE

{
    "password": "this is zoe3"
}

###

GET {{host}}/user/profile
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY2NTgzNTZhM2YzMGU2ZTg1ZDI2NDI4ZCIsImlhdCI6MTcxNzA2NzIwNCwiZXhwIjoxNzE3MzI2NDA0fQ.H1DxhNu8ZJMEEr2HJ4hNNsWYE2mnt7xzjm61zIzvXWE

###

PATCH {{host}}/user/profile
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY2NTgzNTZhM2YzMGU2ZTg1ZDI2NDI4ZCIsImlhdCI6MTcxNzA2NzIwNCwiZXhwIjoxNzE3MzI2NDA0fQ.H1DxhNu8ZJMEEr2HJ4hNNsWYE2mnt7xzjm61zIzvXWE

{
    "nickname": " Zoe3  "
}
